apiVersion: v1
kind: Service
metadata:
  name: {{ include "rymedb.fullname" . }}
  labels:
    {{- include "rymedb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rymedb
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: pg
      port: {{ .Values.service.pg }}
      targetPort: pg
    - name: resp
      port: {{ .Values.service.resp }}
      targetPort: resp
    - name: http
      port: {{ .Values.service.http }}
      targetPort: http
