apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rymedb.fullname" . }}
  labels:
    {{- include "rymedb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rymedb.headless" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rymedb
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rymedb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ryme-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "/etc/rymedb/entrypoint.sh"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RYME_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiKeySecret.name }}
                  key: {{ .Values.apiKeySecret.key }}
          ports:
            - name: pg
              containerPort: {{ .Values.service.pg }}
            - name: resp
              containerPort: {{ .Values.service.resp }}
            - name: http
              containerPort: {{ .Values.service.http }}
            - name: raft
              containerPort: {{ .Values.service.raft }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/rymedb
            - name: entrypoint
              mountPath: /etc/rymedb/entrypoint.sh
              subPath: entrypoint.sh
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: entrypoint
          configMap:
            name: {{ include "rymedb.fullname" . }}-entrypoint
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with .Values.persistence.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
